# Please ensure that atleast one of ["secretBinding","k8sSecret"] are filled. 
# SLV may not work as expected without a secret key or binding specified.

# The secretBinding String
secretBinding: ""


# The name of the secret in the Kubernetes cluster that contains the secretKey or the secretBinding. 
# The secretKey is to be put inside the key name "SecretKey".
# (or)
# The secretBinding is to be put inside the key name "SecretBinding". 
# Ensure that this exists in the same namespace as the release namespace.
k8sSecret: ""

# Name of the job to run
jobName: "slv-job"

# The image with tag to be used for SLV
# You must ensure that the tag that you use is the same as Chart.Version
# Otherwise, helm will throw an error.
image: ""
# The image pull policy.
imagePullPolicy: IfNotPresent

# Setting resource constraints for the operator.
resource:
  # Resource limits 
  limits:
    cpu: "250m" 
    memory: "250Mi" 
  # Resource requests 
  requests:
    cpu: "250m" 
    memory: "250Mi" 

# The labels to be set for the Deployment/CronJob/Job
labels: {}

# The pod Labels to be set for SLV pods.
podLabels: {}

# The name with which the serviceAccount to be attached to the SLV Job. 
# If you set this value, the helm chart will not set up cluster roles or cluster role bindings. 
# You will have to make sure that the service account attached has necessary permissions for SLV to run smoothly. 
# Understand the consequenses of filling this value carefully.
serviceAccountName: ""

# The number of times kubernetes must retry the job in case of failure.
# This is only applicable when the mode is set to "job" or "cronjob".
backoffLimit: 4

# The number of seconds after which the job must be deleted after it has finished.
# This is only applicable when the mode is set to "job" or "cronjob".
ttlSecondsAfterFinished: 3600

# When set, the job will be run as a "Cronjob". The field specifies how frequently the cronjob has to run.
# schedule: "0 * * * *" # Runs at the top of every hour
