---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate
  failurePolicy: Fail
  name: validate-slv
  rules:
  - apiGroups:
    - slv.sh
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - slvs
  sideEffects: None
