{{- if .Values.schedule -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: slv-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    app: slv-cronjob
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished | default 0 }}
      template:
        metadata:
          name: slv-cronjob
          namespace: {{ .Release.Namespace }}
          labels:
            app: slv-cronjob
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
          {{- include "slvlib.container" . | nindent 12 }}
                - name: SLV_MODE
                  value: "k8s_job"
          restartPolicy: Never
          serviceAccountName: {{ .Values.serviceAccountName | default "slv-serviceaccount" }}
      backoffLimit: {{ .Values.backoffLimit | default 4 }}
{{- end}}
