{{- if not .Values.schedule -}}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{.Values.jobName | default "slv-job"}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: slv-job
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished | default 3600 }}
  template:
    metadata:
      name: slv-job
      namespace: {{ .Release.Namespace }}
      labels:
        app: slv-job
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      {{- include "slvlib.container" . | nindent 8 }}
            - name: SLV_MODE
              value: "k8s_job"
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccountName | default "slv-serviceaccount" }}
  backoffLimit: {{ .Values.backoffLimit | default 4 }}
  {{- end -}}
