---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - slv.sh
  resources:
  - slvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slv.sh
  resources:
  - slvs/finalizers
  verbs:
  - update
- apiGroups:
  - slv.sh
  resources:
  - slvs/status
  verbs:
  - get
  - patch
  - update
